version: '3'
services:
  web:
    image: httpd:latest
    ports:
      - "9000:80"
    volumes:
      - ./mapmint/public_map/PointCloud:/usr/local/apache2/htdocs/PointCloud
      - ./mapmint/public_map/PointCloud/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./mapmint/public_map/PointCloud/upload.py:/usr/local/apache2/cgi-bin/upload.py

  zookernel:
    build: .
    image: geolabs/mapmint
    ports:
      - "80:80"
    volumes:
      - ./docker/main.cfg:/usr/lib/cgi-bin/main.cfg
      - ./docker/oas.cfg:/usr/lib/cgi-bin/oas.cfg
      - ./docker/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./zoo-project/zoo-services/utils/open-api/server/publish.py:/usr/lib/cgi-bin/publish.py
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/usr/lib/cgi-bin/subscriber.py
      - ./docker/.htaccess:/var/www/html/.htaccess
      - ./zoo-project/zoo-services/utils/open-api/templates/index.html:/var/www/index.html
      - ./zoo-project/zoo-services/utils/open-api/static:/var/www/html/static
      - ./mapmint/mapmint-ui/templates/generation_bs.tmpl:/mapmint/mapmint-ui/templates/generation_bs.tmpl
      - ./zoo-project/zoo-services/PointCloud/cgi-env/generation.py:/usr/lib/cgi-bin/generation.py  
      - ./zoo-project/zoo-services/PointCloud/cgi-env/PointCloud.zcfg:/usr/lib/cgi-bin/PointCloud.zcfg   
      - ./mapmint/public_map/PointCloud:/var/www/html/PointCloud
      - ./mapmint/public_map/PointCloud/upload.py:/usr/lib/cgi-bin/upload.py 
      - ./mapmint/mapmint-ui/templates/test.tmpl:/mapmint/mapmint-ui/templates/test_display.tmpl
      - ./mapmint/mapmint-ui/templates/result.tmpl:/mapmint/mapmint-ui/templates/result_display.tmpl
      - ./mapmint:/mapmint



    depends_on:
      - pgbouncer
    environment:
      - LC_ALL=en_US.utf-8
      - LANG=en_US.itf-8
      - ZOO_REDIS_HOST=redis
  websocketd:
    build: ./docker/websocketd
    ports:
      - 8888:8888
    environment:
      - ZOO_REDIS_HOST=redis
    volumes:
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/shell.py
    command: ["--port=8888", "/shell.py"]
  pg:
    image: postgis/postgis:10-2.5-alpine #postgres:9.6.18-alpine
    restart: always
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DB: zoo
    volumes:
      # Load the zoo kernel schema
      - ./zoo-project/zoo-kernel/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./mapmint/template/sql/mmdb.sql:/docker-entrypoint-initdb.d/2-mmdb.sql
      - ./mapmint/template/sql/indicators.sql:/docker-entrypoint-initdb.d/3-indicators.sql
      - ./mapmint/template/sql/tables.sql:/docker-entrypoint-initdb.d/4-tables.sql
  pgbouncer:
    image: edoburu/pgbouncer:1.8.1
    environment:
      DATABASE_URL: "postgres://zoo:zoo@pg/zoo"
      MAX_CLIENT_CONN: 1000
      MAX_DB_CONNECTIONS: 100
      DEFAULT_POOL_SIZE: 100
      POOL_MODE: transaction
    ports:
      - "5432:5432"
    depends_on:
      - pg
  redis:
    image: redis:6.0.9